#如果你的终端支持ANSI，设置彩色输出会让日志更具可读性。
#NEVER：禁用ANSI-colored输出（默认项）
#DETECT：会检查终端是否支持ANSI，是的话就采用彩色输出（推荐项）
#ALWAYS：总是使用ANSI-colored格式输出，若终端不支持的时候，会有很多干扰信息，不推荐使用
spring:
  mvc:
    favicon:
      enabled: false
  profiles:
    active: localhost
  output:
    ansi:
      enabled: detect
  freemarker:
    cache: false
    request-context-attribute: request
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true


banner:
  charset: utf-8
  location: banner.txt
logging:
  file: taoquan.log
  level:
    org:
      quartz: error
      springframework: error
    root: info